In [1]:
import requests
import json
from pathlib import Path

In [2]:
manifest_url = "https://emis.education.gov.ng/portal/api/6666cd76f96956469e7be39d750cc7d9/d41d8cd98f00b204e9800998ecf8427e/all-queries.json"

response = requests.get(manifest_url)

print("Status code:", response.status_code)
print("Content type:", response.headers.get("content-type"))

Status code: 200
Content type: application/json

In [3]:
manifest = response.json()

print(type(manifest))
print("Number of entries:", len(manifest))

<class 'dict'>
Number of entries: 111

In [4]:
list(manifest.keys())[:20]

['kpis_total_columns',
 'kpis_total_length',
 'kpis_total_data',
 'kpis_public_columns',
 'kpis_public_length',
 'kpis_public_data',
 'kpis_private_columns',
 'kpis_private_length',
 'kpis_private_data',
 'reporting_columns',
 'reporting_length',
 'reporting_data',
 'benchmark_columns',
 'benchmark_length',
 'benchmark_data',
 'enrol_total_columns',
 'enrol_total_length',
 'enrol_total_data',
 'enrol_public_columns',
 'enrol_public_length']

In [5]:
keywords = [
    "kpi",
    "report",
    "benchmark",
    "enrol",
    "teacher",
    "class",
    "lga",
    "state",
    "public",
    "private"
]

relevant_keys = [
    key for key in manifest.keys()
    if any(word in key.lower() for word in keywords)
]

for key in relevant_keys:
    print(key)

kpis_total_columns
kpis_total_length
kpis_total_data
kpis_public_columns
kpis_public_length
kpis_public_data
kpis_private_columns
kpis_private_length
kpis_private_data
reporting_columns
reporting_length
reporting_data
benchmark_columns
benchmark_length
benchmark_data
enrol_total_columns
enrol_total_length
enrol_total_data
enrol_public_columns
enrol_public_length
enrol_public_data
enrol_private_columns
enrol_private_length
enrol_private_data
sex_public_columns
sex_public_length
sex_public_data
sex_private_columns
sex_private_length
sex_private_data
schools_public_columns
schools_public_length
schools_public_data
schools_private_columns
schools_private_length
schools_private_data
ownership_enrol_columns
ownership_enrol_length
ownership_enrol_data
children_map_public_columns
children_map_public_length
children_map_public_data
children_map_private_columns
children_map_private_length
children_map_private_data
lvl_total_public_columns
lvl_total_public_length
lvl_total_public_data
lvl_total_private_columns
lvl_total_private_length
lvl_total_private_data
lvl_primary_public_columns
lvl_primary_public_length
lvl_primary_public_data
lvl_primary_private_columns
lvl_primary_private_length
lvl_primary_private_data
lvl_jss_public_columns
lvl_jss_public_length
lvl_jss_public_data
lvl_jss_private_columns
lvl_jss_private_length
lvl_jss_private_data
lvl_sss_public_columns
lvl_sss_public_length
lvl_sss_public_data
lvl_sss_private_columns
lvl_sss_private_length
lvl_sss_private_data
lvl_iqs_public_columns
lvl_iqs_public_length
lvl_iqs_public_data
lvl_iqs_private_columns
lvl_iqs_private_length
lvl_iqs_private_data
lvl_techvoc_public_columns
lvl_techvoc_public_length
lvl_techvoc_public_data
lvl_techvoc_private_columns
lvl_techvoc_private_length
lvl_techvoc_private_data

In [6]:
len(relevant_keys)

81

In [7]:
raw_dir = Path("../data/raw/dnemis/2024_2025")
raw_dir.mkdir(parents=True, exist_ok=True)

In [8]:
manifest_path = raw_dir / "all-queries.json"

manifest_path.write_text(
    response.text,
    encoding="utf-8"
)

print(manifest_path)

..\data\raw\dnemis\2024_2025\all-queries.json

In [9]:
for key in relevant_keys:
    print(key, "->", manifest[key])

kpis_total_columns -> 59d0107b86b52b345462334f59aba9df
kpis_total_length -> 58551acc587eaa879c80b8d24b44fcd2
kpis_total_data -> da983008b60d92a2b028f9f8228442cf
kpis_public_columns -> 59d0107b86b52b345462334f59aba9df
kpis_public_length -> 58551acc587eaa879c80b8d24b44fcd2
kpis_public_data -> 7981ead9fbf3d484d5b9a163fe9de92d
kpis_private_columns -> 59d0107b86b52b345462334f59aba9df
kpis_private_length -> 58551acc587eaa879c80b8d24b44fcd2
kpis_private_data -> 3f658ee6eb4d6cb2dc0e1eaba566287f
reporting_columns -> ef5a06ba30fc4c90805cb19d8986a556
reporting_length -> 8b0eb180b8979e40dfcaffe1d7eea9a9
reporting_data -> 2a27b50e430b87481c21aac68a0ccfa5
benchmark_columns -> cf45072fb20e2a902fe025c2294e2c46
benchmark_length -> dfa21de6fb926c9238530844f3ca421c
benchmark_data -> 36be050e8a30f2e268bbedf3202025a4
enrol_total_columns -> c2b78c07d07b71a23b58d12aabc167a9
enrol_total_length -> af7dbb9efde103c1759e984314af2aad
enrol_total_data -> af603f596855851efb442dc7abad9f49
enrol_public_columns -> c2b78c07d07b71a23b58d12aabc167a9
enrol_public_length -> af7dbb9efde103c1759e984314af2aad
enrol_public_data -> 6763ecda452f7ea20b169c1679b0dbd5
enrol_private_columns -> c2b78c07d07b71a23b58d12aabc167a9
enrol_private_length -> af7dbb9efde103c1759e984314af2aad
enrol_private_data -> 725cf6546cbae3732c30b413c15de9e6
sex_public_columns -> 72ce96b2eb1db3843cffcef3afe570bc
sex_public_length -> 0d891973ed8221c54b646748cdd05e3f
sex_public_data -> d421caef6f03a3f5d19b1558632ca317
sex_private_columns -> 72ce96b2eb1db3843cffcef3afe570bc
sex_private_length -> 0d891973ed8221c54b646748cdd05e3f
sex_private_data -> 461ebbd584e034a5ae0cb9aff4fcbe94
schools_public_columns -> 192d7300a77e7cc0e323af999fb7f972
schools_public_length -> af7dbb9efde103c1759e984314af2aad
schools_public_data -> 86ae6d20d9bbb959db69b995a13b1fc8
schools_private_columns -> 192d7300a77e7cc0e323af999fb7f972
schools_private_length -> 8b0eb180b8979e40dfcaffe1d7eea9a9
schools_private_data -> 0cf49a6cabb79c7d1ed547ca2a156757
ownership_enrol_columns -> ce727dee58845380a0ee402c09c15f63
ownership_enrol_length -> 8b0eb180b8979e40dfcaffe1d7eea9a9
ownership_enrol_data -> 2d7a9c269a2a1e64d18d8207e393ba19
children_map_public_columns -> 3af940b2f415118af2d6036d870edc34
children_map_public_length -> 2a7b30b00ec9146982bc959549f1eb23
children_map_public_data -> 4664356dac8fdbbb4e57366dad2bd8cf
children_map_private_columns -> 3af940b2f415118af2d6036d870edc34
children_map_private_length -> 2a7b30b00ec9146982bc959549f1eb23
children_map_private_data -> dd4c6eeb497485a5d729bcd1ff4a5d6d
lvl_total_public_columns -> 302e11781687429fd819dbf70e1136a7
lvl_total_public_length -> 032f6c542bb421526fd41a9f2db79609
lvl_total_public_data -> d32f421a6a2017a63706f0ca86ade662
lvl_total_private_columns -> 302e11781687429fd819dbf70e1136a7
lvl_total_private_length -> 032f6c542bb421526fd41a9f2db79609
lvl_total_private_data -> f19ab984134018e82d9d1b7f2ed6e2f0
lvl_primary_public_columns -> 302e11781687429fd819dbf70e1136a7
lvl_primary_public_length -> 032f6c542bb421526fd41a9f2db79609
lvl_primary_public_data -> 3996eeb1839b23767c16973462c6a303
lvl_primary_private_columns -> 302e11781687429fd819dbf70e1136a7
lvl_primary_private_length -> 032f6c542bb421526fd41a9f2db79609
lvl_primary_private_data -> 419a51afede37148514bba3683ae3a28
lvl_jss_public_columns -> 302e11781687429fd819dbf70e1136a7
lvl_jss_public_length -> 032f6c542bb421526fd41a9f2db79609
lvl_jss_public_data -> af52555b0172947d639b61c42b23d4c0
lvl_jss_private_columns -> 302e11781687429fd819dbf70e1136a7
lvl_jss_private_length -> 032f6c542bb421526fd41a9f2db79609
lvl_jss_private_data -> 067f85707a7cfd38df0573586c4e3fac
lvl_sss_public_columns -> 302e11781687429fd819dbf70e1136a7
lvl_sss_public_length -> 032f6c542bb421526fd41a9f2db79609
lvl_sss_public_data -> e8037be392db9f83b3b4b3346dc41903
lvl_sss_private_columns -> 302e11781687429fd819dbf70e1136a7
lvl_sss_private_length -> 032f6c542bb421526fd41a9f2db79609
lvl_sss_private_data -> 09fb59f16bebe22566b6897202ed8030
lvl_iqs_public_columns -> 302e11781687429fd819dbf70e1136a7
lvl_iqs_public_length -> 032f6c542bb421526fd41a9f2db79609
lvl_iqs_public_data -> 87d7df177f8d4b669772d7981f8f9d1c
lvl_iqs_private_columns -> 302e11781687429fd819dbf70e1136a7
lvl_iqs_private_length -> 032f6c542bb421526fd41a9f2db79609
lvl_iqs_private_data -> 142e5a86e30ec09844b2b2b2eaf82384
lvl_techvoc_public_columns -> 302e11781687429fd819dbf70e1136a7
lvl_techvoc_public_length -> 032f6c542bb421526fd41a9f2db79609
lvl_techvoc_public_data -> 2a8f0f40169c9b0480ed1c169664a50f
lvl_techvoc_private_columns -> 302e11781687429fd819dbf70e1136a7
lvl_techvoc_private_length -> 032f6c542bb421526fd41a9f2db79609
lvl_techvoc_private_data -> 142e5a86e30ec09844b2b2b2eaf82384

In [10]:
for key in relevant_keys:
    print(key)

kpis_total_columns
kpis_total_length
kpis_total_data
kpis_public_columns
kpis_public_length
kpis_public_data
kpis_private_columns
kpis_private_length
kpis_private_data
reporting_columns
reporting_length
reporting_data
benchmark_columns
benchmark_length
benchmark_data
enrol_total_columns
enrol_total_length
enrol_total_data
enrol_public_columns
enrol_public_length
enrol_public_data
enrol_private_columns
enrol_private_length
enrol_private_data
sex_public_columns
sex_public_length
sex_public_data
sex_private_columns
sex_private_length
sex_private_data
schools_public_columns
schools_public_length
schools_public_data
schools_private_columns
schools_private_length
schools_private_data
ownership_enrol_columns
ownership_enrol_length
ownership_enrol_data
children_map_public_columns
children_map_public_length
children_map_public_data
children_map_private_columns
children_map_private_length
children_map_private_data
lvl_total_public_columns
lvl_total_public_length
lvl_total_public_data
lvl_total_private_columns
lvl_total_private_length
lvl_total_private_data
lvl_primary_public_columns
lvl_primary_public_length
lvl_primary_public_data
lvl_primary_private_columns
lvl_primary_private_length
lvl_primary_private_data
lvl_jss_public_columns
lvl_jss_public_length
lvl_jss_public_data
lvl_jss_private_columns
lvl_jss_private_length
lvl_jss_private_data
lvl_sss_public_columns
lvl_sss_public_length
lvl_sss_public_data
lvl_sss_private_columns
lvl_sss_private_length
lvl_sss_private_data
lvl_iqs_public_columns
lvl_iqs_public_length
lvl_iqs_public_data
lvl_iqs_private_columns
lvl_iqs_private_length
lvl_iqs_private_data
lvl_techvoc_public_columns
lvl_techvoc_public_length
lvl_techvoc_public_data
lvl_techvoc_private_columns
lvl_techvoc_private_length
lvl_techvoc_private_data

In [11]:
base_url = manifest_url.rsplit("/", 1)[0] + "/"

print(base_url)

https://emis.education.gov.ng/portal/api/6666cd76f96956469e7be39d750cc7d9/d41d8cd98f00b204e9800998ecf8427e/

In [12]:
key = "kpis_total_data"

file_hash = manifest[key]
arrow_url = f"{base_url}{file_hash}.arrow"

print(key)
print(file_hash)
print(arrow_url)

kpis_total_data
da983008b60d92a2b028f9f8228442cf
https://emis.education.gov.ng/portal/api/6666cd76f96956469e7be39d750cc7d9/d41d8cd98f00b204e9800998ecf8427e/da983008b60d92a2b028f9f8228442cf.arrow

In [13]:
arrow_response = requests.get(arrow_url)

print("Status:", arrow_response.status_code)
print("Content type:", arrow_response.headers.get("content-type"))
print("Size:", len(arrow_response.content), "bytes")

Status: 200
Content type: text/html
Size: 5189 bytes

In [14]:
arrow_path = raw_dir / "kpis_total_data.arrow"

arrow_path.write_bytes(arrow_response.content)

print("Saved:", arrow_path)

Saved: ..\data\raw\dnemis\2024_2025\kpis_total_data.arrow

In [15]:
import pyarrow.ipc as ipc

In [16]:
with open(arrow_path, "rb") as f:
    reader = ipc.open_file(f)
    table = reader.read_all()

table

ArrowInvalid: Not an Arrow file

In [17]:
with open(arrow_path, "rb") as f:
    reader = ipc.open_stream(f)
    table = reader.read_all()

table

ArrowInvalid: Expected to read 1868833084 metadata bytes, but only read 5185

In [18]:
print("Status:", arrow_response.status_code)
print("Content-Type:", arrow_response.headers.get("content-type"))
print("Content-Encoding:", arrow_response.headers.get("content-encoding"))
print("First 32 bytes:", arrow_response.content[:32])
print("File size:", len(arrow_response.content))

Status: 200
Content-Type: text/html
Content-Encoding: gzip
First 32 bytes: b'<!doctype html>\n<html lang="en">'
File size: 5189

In [19]:
with open(arrow_path, "rb") as f:
    first_bytes = f.read(32)

print(first_bytes)

b'<!doctype html>\n<html lang="en">'

In [21]:
arrow_base_url = "https://emis.education.gov.ng/portal/api/prerendered_queries/"

In [22]:
key = "kpis_total_data"

file_hash = manifest[key]

arrow_url = f"{arrow_base_url}{file_hash}.arrow"

print(arrow_url)

https://emis.education.gov.ng/portal/api/prerendered_queries/da983008b60d92a2b028f9f8228442cf.arrow

In [23]:
arrow_response = requests.get(arrow_url)

print("Status:", arrow_response.status_code)
print("Content-Type:", arrow_response.headers.get("content-type"))
print("File size:", len(arrow_response.content))
print("First 32 bytes:", arrow_response.content[:32])

Status: 200
Content-Type: application/octet-stream
File size: 504
First 32 bytes: b'\xff\xff\xff\xff\xb0\x00\x00\x00\x10\x00\x00\x00\x00\x00\n\x00\x10\x00\x0e\x00\x07\x00\x08\x00\n\x00\x00\x00\x00\x00\x00\x01'

In [24]:
arrow_path = raw_dir / "kpis_total_data.arrow"

arrow_path.write_bytes(arrow_response.content)

print("Saved:", arrow_path)

Saved: ..\data\raw\dnemis\2024_2025\kpis_total_data.arrow

In [25]:
import pyarrow.ipc as ipc

with open(arrow_path, "rb") as f:
    reader = ipc.open_stream(f)
    table = reader.read_all()

table

pyarrow.Table
dx: string
value: double
----
dx: [["jwjKmtVK2wj","Dw7f4gs9RcS","DvMfSq5pZSA","vDmeu4io2Fs"]]
value: [[39825932,1185610,725778,604479]]

In [27]:
def download_arrow(logical_key):
    file_hash = manifest[logical_key]
    url = f"{arrow_base_url}{file_hash}.arrow"

    r = requests.get(url)
    r.raise_for_status()

    print(
        logical_key,
        "|",
        r.status_code,
        "|",
        r.headers.get("content-type"),
        "|",
        len(r.content),
        "bytes"
    )

    path = raw_dir / f"{logical_key}.arrow"
    path.write_bytes(r.content)

    with open(path, "rb") as f:
        reader = ipc.open_stream(f)
        table = reader.read_all()

    return table.to_pandas()

In [28]:
kpis_columns = download_arrow("kpis_total_columns")

display(kpis_columns)

kpis_total_columns | 200 | application/octet-stream | 1016 bytes

  column_name column_type null  key default extra
0          dx     VARCHAR  YES  NaN     NaN   NaN
1       value      DOUBLE  YES  NaN     NaN   NaN

In [29]:
kpis_length = download_arrow("kpis_total_length")
display(kpis_length)

kpis_total_length | 200 | application/octet-stream | 304 bytes

   rowCount
0       4.0

In [30]:
kpis_data = download_arrow("kpis_total_data")

kpis_total_data | 200 | application/octet-stream | 504 bytes

In [31]:
print("=== COLUMNS ===")
display(kpis_columns)

print("=== LENGTH ===")
display(kpis_length)

print("=== DATA ===")
display(kpis_data)

=== COLUMNS ===

  column_name column_type null  key default extra
0          dx     VARCHAR  YES  NaN     NaN   NaN
1       value      DOUBLE  YES  NaN     NaN   NaN

=== LENGTH ===

   rowCount
0       4.0

=== DATA ===

            dx       value
0  jwjKmtVK2wj  39825932.0
1  Dw7f4gs9RcS   1185610.0
2  DvMfSq5pZSA    725778.0
3  vDmeu4io2Fs    604479.0

In [32]:
print("Columns shape:", kpis_columns.shape)
print("Length shape:", kpis_length.shape)
print("Data shape:", kpis_data.shape)

Columns shape: (2, 6)
Length shape: (1, 1)
Data shape: (4, 2)

In [33]:
reporting_data = download_arrow("reporting_data")
benchmark_data = download_arrow("benchmark_data")

display(reporting_data)
display(benchmark_data)

reporting_data | 200 | application/octet-stream | 1352 bytes
benchmark_data | 200 | application/octet-stream | 2208 bytes

      mode  submitted  expected  completeness
0    total   124066.0  230844.0          53.7
1   public    83839.0  113723.0          73.7
2  private    40227.0  117121.0          34.3

       mode  ord                indicator    fmt   std   unit  state
0   private    1    Learner–Teacher Ratio  ratio  35.0   13.8    NaN
1   private    2  Learner–Classroom Ratio  ratio  35.0   37.9    NaN
2   private    3     Learner–Toilet Ratio  ratio  30.0   39.2    NaN
3   private    4     Learner–School Ratio  ratio   NaN   70.8    NaN
4   private    5      Female Learners (%)    pct   NaN   50.4    NaN
5   private    6      Female Teachers (%)    pct   NaN   60.1    NaN
6    public    1    Learner–Teacher Ratio  ratio  35.0   53.9    NaN
7    public    2  Learner–Classroom Ratio  ratio  35.0   60.1    NaN
8    public    3     Learner–Toilet Ratio  ratio  30.0   80.1    NaN
9    public    4     Learner–School Ratio  ratio   NaN  280.8    NaN
10   public    5      Female Learners (%)    pct   NaN   49.4    NaN
11   public    6      Female Teachers (%)    pct   NaN   51.1    NaN
12    total    1    Learner–Teacher Ratio  ratio  35.0   33.6    NaN
13    total    2  Learner–Classroom Ratio  ratio  35.0   60.1    NaN
14    total    3     Learner–Toilet Ratio  ratio  30.0   65.9    NaN
15    total    4     Learner–School Ratio  ratio   NaN  173.0    NaN
16    total    5      Female Learners (%)    pct   NaN   49.6    NaN
17    total    6      Female Teachers (%)    pct   NaN   55.7    NaN

In [34]:
print(reporting_data.columns.tolist())
print(benchmark_data.columns.tolist())

['mode', 'submitted', 'expected', 'completeness']
['mode', 'ord', 'indicator', 'fmt', 'std', 'unit', 'state']

In [35]:
children_map_public = download_arrow("children_map_public_data")
display(children_map_public.head(20))
print(children_map_public.columns.tolist())
print(children_map_public.shape)

children_map_public_data | 200 | application/octet-stream | 3248 bytes

             id            name   learners                           link
0   M689V9w3Gs3     Kebbi State   952498.0  /portal/asc/state-M689V9w3Gs3
1   FHlOerryBjk      Abia State   707447.0  /portal/asc/state-FHlOerryBjk
2   OgjFloqKoqk   Adamawa State  1155465.0  /portal/asc/state-OgjFloqKoqk
3   aMQcvAoEFh0       Edo State   533357.0  /portal/asc/state-aMQcvAoEFh0
4   cTIw3RXOLCQ      Kano State  5055435.0  /portal/asc/state-cTIw3RXOLCQ
5   uKlacgs9ykR   Katsina State  1920270.0  /portal/asc/state-uKlacgs9ykR
6   FmH4buccgqx   Zamfara State   962658.0  /portal/asc/state-FmH4buccgqx
7   FmOhtDnhdwU       Imo State  1243543.0  /portal/asc/state-FmOhtDnhdwU
8   Gq37IyyjUfj    Sokoto State  1162481.0  /portal/asc/state-Gq37IyyjUfj
9   H2ZhSMudlMI     Lagos State   865124.0  /portal/asc/state-H2ZhSMudlMI
10  MJVVi73YayJ    Jigawa State  1567300.0  /portal/asc/state-MJVVi73YayJ
11  MXrZyuS9E7A     Benue State   153665.0  /portal/asc/state-MXrZyuS9E7A
12  Nko8QFDmYmq   Anambra state   151457.0  /portal/asc/state-Nko8QFDmYmq
13  Quac4RHRtaZ     Enugu State   364227.0  /portal/asc/state-Quac4RHRtaZ
14  fBInDsbaQHO      Ogun State   449681.0  /portal/asc/state-fBInDsbaQHO
15  gzLOszDWdqM  Nasarawa State    43168.0  /portal/asc/state-gzLOszDWdqM
16  hfNPq5F4mjr      Osun State   234708.0  /portal/asc/state-hfNPq5F4mjr
17  iilma7EajGc     Ekiti State   286517.0  /portal/asc/state-iilma7EajGc
18  jReUW6NCPkL     Kwara State   482705.0  /portal/asc/state-jReUW6NCPkL
19  Ym1fEhWFWYI      Yobe State   972936.0  /portal/asc/state-Ym1fEhWFWYI

['id', 'name', 'learners', 'link']
(36, 4)

In [36]:
lvl_total_public = download_arrow("lvl_total_public_data")
display(lvl_total_public.head(20))
print(lvl_total_public.columns.tolist())
print(lvl_total_public.shape)

lvl_total_public_data | 200 | application/octet-stream | 5056 bytes

,ou_name,link,enrolment,female_l,lt,lc,ltoilet,femt,special
0,Abia State,/portal/asc/state-FHlOerryBjk,707447.0,50.1,72.0,74.4,635.1,87.9,3834.0
1,Adamawa State,/portal/asc/state-OgjFloqKoqk,1155465.0,49.2,44.6,56.2,209.6,38.5,10295.0
2,Akwa-Ibom State,/portal/asc/state-qLiKWoddwFu,474968.0,51.4,31.5,47.9,160.7,65.5,2365.0
3,Anambra state,/portal/asc/state-Nko8QFDmYmq,151457.0,49.4,24.0,22.7,88.1,87.8,1935.0
4,Bauchi State,/portal/asc/state-ziJ3yxfgb3m,1540733.0,48.1,69.6,67.0,266.9,32.4,16363.0
5,Bayelsa State,/portal/asc/state-ns3vF75Y0bF,177727.0,50.7,25.2,24.2,86.7,54.4,263.0
6,Benue State,/portal/asc/state-MXrZyuS9E7A,153665.0,49.9,30.5,22.9,52.7,39.3,1115.0
7,Borno State,/portal/asc/state-RLySnRCE1Gy,914508.0,49.2,59.9,84.8,119.5,45.8,4596.0
8,Cross River State,/portal/asc/state-caG44DzHu6F,8254.0,50.1,13.5,21.2,69.4,62.8,61.0
9,Delta State,/portal/asc/state-m0rZG06GdPe,294821.0,49.8,23.2,20.7,117.5,77.2,1298.0
10,Ebonyi State,/portal/asc/state-xWSEoKmrbBW,340728.0,52.1,32.3,32.7,371.2,57.1,3389.0
11,Edo State,/portal/asc/state-aMQcvAoEFh0,533357.0,36.4,49.5,43.2,45.4,67.8,4319.0
12,Ekiti State,/portal/asc/state-iilma7EajGc,286517.0,51.6,18.4,28.2,80.1,70.9,3396.0
13,Enugu State,/portal/asc/state-Quac4RHRtaZ,364227.0,51.8,17.1,25.2,1.7,77.6,1760.0
14,Federal Capital Territory,/portal/asc/state-HYCMnXqLDPV,299697.0,51.4,18.7,40.7,79.0,57.3,3504.0
15,Gombe,/portal/asc/state-bSfaEpPFa9Y,549515.0,48.9,37.6,58.0,177.2,40.5,7685.0
16,Imo State,/portal/asc/state-FmOhtDnhdwU,1243543.0,50.4,82.2,75.7,1090.8,87.4,6748.0
17,Jigawa State,/portal/asc/state-MJVVi73YayJ,1567300.0,49.4,72.8,77.6,146.7,19.4,16567.0
18,Kaduna State,/portal/asc/state-tjLatcokcel,2418794.0,49.9,72.7,57.0,197.0,51.6,16001.0
19,Kano State,/portal/asc/state-cTIw3RXOLCQ,5055435.0,52.2,92.6,93.1,223.3,32.3,32235.0

['ou_name', 'link', 'enrolment', 'female_l', 'lt', 'lc', 'ltoilet', 'femt', 'special']
(37, 9)

In [37]:
lagos = children_map_public[
    children_map_public["name"].str.contains(
        "Lagos",
        case=False,
        na=False
    )
]

display(lagos)

            id         name  learners                           link
9  H2ZhSMudlMI  Lagos State  865124.0  /portal/asc/state-H2ZhSMudlMI

In [38]:
lagos_link = lagos.iloc[0]["link"]

print(lagos_link)

/portal/asc/state-H2ZhSMudlMI

In [39]:
site_root = "https://emis.education.gov.ng"

lagos_url = site_root + lagos_link

print(lagos_url)

https://emis.education.gov.ng/portal/asc/state-H2ZhSMudlMI

In [40]:
lagos_response = requests.get(lagos_url)

print("Status:", lagos_response.status_code)
print("Content-Type:", lagos_response.headers.get("content-type"))
print("Length:", len(lagos_response.text))

Status: 200
Content-Type: text/html
Length: 145468

In [41]:
html = lagos_response.text

print("all-queries.json" in html)
print("prerendered_queries" in html)

False
False

In [42]:
lagos_manifest_url = "https://emis.education.gov.ng/portal/api/5ef846daf4b912ae3002fb35d3130e07/d41d8cd98f00b204e9800998ecf8427e/all-queries.json"

In [43]:
lagos_response = requests.get(lagos_manifest_url)

print("Status:", lagos_response.status_code)
print("Content-Type:", lagos_response.headers.get("content-type"))

lagos_manifest = lagos_response.json()

print("Entries:", len(lagos_manifest))
print(list(lagos_manifest.keys())[:30])

Status: 200
Content-Type: application/json
Entries: 111
['kpis_total_columns', 'kpis_total_length', 'kpis_total_data', 'kpis_public_columns', 'kpis_public_length', 'kpis_public_data', 'kpis_private_columns', 'kpis_private_length', 'kpis_private_data', 'reporting_columns', 'reporting_length', 'reporting_data', 'benchmark_columns', 'benchmark_length', 'benchmark_data', 'enrol_total_columns', 'enrol_total_length', 'enrol_total_data', 'enrol_public_columns', 'enrol_public_length', 'enrol_public_data', 'enrol_private_columns', 'enrol_private_length', 'enrol_private_data', 'sex_total_columns', 'sex_total_length', 'sex_total_data', 'sex_public_columns', 'sex_public_length', 'sex_public_data']

In [44]:
for key in lagos_manifest.keys():
    if any(word in key.lower() for word in [
        "child",
        "map",
        "lga",
        "kpi",
        "report",
        "benchmark",
        "public",
        "private",
        "level"
    ]):
        print(key)

kpis_total_columns
kpis_total_length
kpis_total_data
kpis_public_columns
kpis_public_length
kpis_public_data
kpis_private_columns
kpis_private_length
kpis_private_data
reporting_columns
reporting_length
reporting_data
benchmark_columns
benchmark_length
benchmark_data
enrol_public_columns
enrol_public_length
enrol_public_data
enrol_private_columns
enrol_private_length
enrol_private_data
sex_public_columns
sex_public_length
sex_public_data
sex_private_columns
sex_private_length
sex_private_data
schools_public_columns
schools_public_length
schools_public_data
schools_private_columns
schools_private_length
schools_private_data
children_map_total_columns
children_map_total_length
children_map_total_data
children_map_public_columns
children_map_public_length
children_map_public_data
children_map_private_columns
children_map_private_length
children_map_private_data
lvl_total_public_columns
lvl_total_public_length
lvl_total_public_data
lvl_total_private_columns
lvl_total_private_length
lvl_total_private_data
lvl_primary_public_columns
lvl_primary_public_length
lvl_primary_public_data
lvl_primary_private_columns
lvl_primary_private_length
lvl_primary_private_data
lvl_jss_public_columns
lvl_jss_public_length
lvl_jss_public_data
lvl_jss_private_columns
lvl_jss_private_length
lvl_jss_private_data
lvl_sss_public_columns
lvl_sss_public_length
lvl_sss_public_data
lvl_sss_private_columns
lvl_sss_private_length
lvl_sss_private_data
lvl_iqs_public_columns
lvl_iqs_public_length
lvl_iqs_public_data
lvl_iqs_private_columns
lvl_iqs_private_length
lvl_iqs_private_data
lvl_techvoc_public_columns
lvl_techvoc_public_length
lvl_techvoc_public_data
lvl_techvoc_private_columns
lvl_techvoc_private_length
lvl_techvoc_private_data

In [45]:
lagos_raw_dir = Path("../data/raw/dnemis/2024_2025/states/lagos")
lagos_raw_dir.mkdir(parents=True, exist_ok=True)

lagos_manifest_path = lagos_raw_dir / "all-queries.json"

lagos_manifest_path.write_text(
    lagos_response.text,
    encoding="utf-8"
)

print("Saved:", lagos_manifest_path)

Saved: ..\data\raw\dnemis\2024_2025\states\lagos\all-queries.json

In [46]:
def download_arrow_from_manifest(
    manifest_obj,
    logical_key,
    output_dir
):
    file_hash = manifest_obj[logical_key]
    url = f"{arrow_base_url}{file_hash}.arrow"

    r = requests.get(url)
    r.raise_for_status()

    print(
        logical_key,
        "|",
        r.status_code,
        "|",
        r.headers.get("content-type"),
        "|",
        len(r.content),
        "bytes"
    )

    path = output_dir / f"{logical_key}.arrow"
    path.write_bytes(r.content)

    with open(path, "rb") as f:
        reader = ipc.open_stream(f)
        table = reader.read_all()

    return table.to_pandas()

In [47]:
lagos_children = download_arrow_from_manifest(
    lagos_manifest,
    "children_map_total_data",
    lagos_raw_dir
)

display(lagos_children)

children_map_total_data | 200 | application/octet-stream | 2072 bytes

             id                  name  learners                         link
0   Phmk9OjyhlF       Ibeju/Lekki LGA   67944.0  /portal/asc/lga/Phmk9OjyhlF
1   wvrTERNJ55l    Lagos Mainland LGA   71994.0  /portal/asc/lga/wvrTERNJ55l
2   WjXjgXuzaRw           Shomolu LGA   48845.0  /portal/asc/lga/WjXjgXuzaRw
3   FNBnbVdc4QR           Eti-Osa LGA   57562.0  /portal/asc/lga/FNBnbVdc4QR
4   O7v1DtGbdbK          Surulere LGA   96161.0  /portal/asc/lga/O7v1DtGbdbK
5   bz52b77hwoM            Mushin LGA   58670.0  /portal/asc/lga/bz52b77hwoM
6   qCnM7T01dCn            Kosofe LGA   94093.0  /portal/asc/lga/qCnM7T01dCn
7   Isx2W2hs7r0      Amuwo Odofin LGA  118677.0  /portal/asc/lga/Isx2W2hs7r0
8   KOlYwQZTBzv       Ifako/Ijaye LGA  144830.0  /portal/asc/lga/KOlYwQZTBzv
9   LPvGvHdlvgi               Ojo LGA  143968.0  /portal/asc/lga/LPvGvHdlvgi
10  SZSJbgQp79d  Ajeromi/Ifelodun LGA   69526.0  /portal/asc/lga/SZSJbgQp79d
11  SrU5MH6HMIM               Epe LGA   84839.0  /portal/asc/lga/SrU5MH6HMIM
12  UCclb3oBhbL             Ikeja LGA   55329.0  /portal/asc/lga/UCclb3oBhbL
13  WgUVHd6LYlp      Oshodi/Isolo LGA   74277.0  /portal/asc/lga/WgUVHd6LYlp
14  ePAmwPgZitO             Agege LGA   60926.0  /portal/asc/lga/ePAmwPgZitO
15  fhB4ICWDhmX          Alimosho LGA  332293.0  /portal/asc/lga/fhB4ICWDhmX
16  x9npNF7jiEr           Badagry LGA  140402.0  /portal/asc/lga/x9npNF7jiEr
17  ugACc96v8dR      Lagos Island LGA   31524.0  /portal/asc/lga/ugACc96v8dR
18  uhzcCCb85FB           Ikorodu LGA  241112.0  /portal/asc/lga/uhzcCCb85FB
19  yme7mbY3bAw             Apapa LGA   43070.0  /portal/asc/lga/yme7mbY3bAw

In [48]:
print(lagos_children.columns.tolist())
print(lagos_children.shape)

['id', 'name', 'learners', 'link']
(20, 4)

In [49]:
lagos_kpis = download_arrow_from_manifest(
    lagos_manifest,
    "kpis_total_data",
    lagos_raw_dir
)

display(lagos_kpis)

kpis_total_data | 200 | application/octet-stream | 504 bytes

            dx      value
0  jwjKmtVK2wj  2036042.0
1  Dw7f4gs9RcS   131636.0
2  DvMfSq5pZSA   102620.0
3  vDmeu4io2Fs    84828.0

In [50]:
lagos_reporting = download_arrow_from_manifest(
    lagos_manifest,
    "reporting_data",
    lagos_raw_dir
)

display(lagos_reporting)

reporting_data | 200 | application/octet-stream | 1352 bytes

      mode  submitted  expected  completeness
0    total    12464.0   14622.0          85.2
1   public     2251.0    2700.0          83.4
2  private    10213.0   11922.0          85.7

In [51]:
lagos_benchmark = download_arrow_from_manifest(
    lagos_manifest,
    "benchmark_data",
    lagos_raw_dir
)

display(lagos_benchmark)

benchmark_data | 200 | application/octet-stream | 2216 bytes

       mode  ord                indicator    fmt   std   unit  state
0   private    1    Learner–Teacher Ratio  ratio  35.0   11.2    NaN
1   private    2  Learner–Classroom Ratio  ratio  35.0    NaN    NaN
2   private    3     Learner–Toilet Ratio  ratio  30.0   18.4    NaN
3   private    4     Learner–School Ratio  ratio   NaN   98.5    NaN
4   private    5      Female Learners (%)    pct   NaN   51.1    NaN
5   private    6      Female Teachers (%)    pct   NaN   69.4    NaN
6    public    1    Learner–Teacher Ratio  ratio  35.0   32.2    NaN
7    public    2  Learner–Classroom Ratio  ratio  35.0   46.4    NaN
8    public    3     Learner–Toilet Ratio  ratio  30.0   40.6    NaN
9    public    4     Learner–School Ratio  ratio   NaN  321.2    NaN
10   public    5      Female Learners (%)    pct   NaN   50.0    NaN
11   public    6      Female Teachers (%)    pct   NaN   71.1    NaN
12    total    1    Learner–Teacher Ratio  ratio  35.0   15.5    NaN
13    total    2  Learner–Classroom Ratio  ratio  35.0   46.4    NaN
14    total    3     Learner–Toilet Ratio  ratio  30.0   24.0    NaN
15    total    4     Learner–School Ratio  ratio   NaN  139.6    NaN
16    total    5      Female Learners (%)    pct   NaN   50.6    NaN
17    total    6      Female Teachers (%)    pct   NaN   69.7    NaN

In [52]:
lagos_children = download_arrow_from_manifest(
    lagos_manifest,
    "children_map_total_data",
    lagos_raw_dir
)

display(lagos_children)

print(lagos_children.columns.tolist())
print(lagos_children.shape)

children_map_total_data | 200 | application/octet-stream | 2072 bytes

             id                  name  learners                         link
0   Phmk9OjyhlF       Ibeju/Lekki LGA   67944.0  /portal/asc/lga/Phmk9OjyhlF
1   wvrTERNJ55l    Lagos Mainland LGA   71994.0  /portal/asc/lga/wvrTERNJ55l
2   WjXjgXuzaRw           Shomolu LGA   48845.0  /portal/asc/lga/WjXjgXuzaRw
3   FNBnbVdc4QR           Eti-Osa LGA   57562.0  /portal/asc/lga/FNBnbVdc4QR
4   O7v1DtGbdbK          Surulere LGA   96161.0  /portal/asc/lga/O7v1DtGbdbK
5   bz52b77hwoM            Mushin LGA   58670.0  /portal/asc/lga/bz52b77hwoM
6   qCnM7T01dCn            Kosofe LGA   94093.0  /portal/asc/lga/qCnM7T01dCn
7   Isx2W2hs7r0      Amuwo Odofin LGA  118677.0  /portal/asc/lga/Isx2W2hs7r0
8   KOlYwQZTBzv       Ifako/Ijaye LGA  144830.0  /portal/asc/lga/KOlYwQZTBzv
9   LPvGvHdlvgi               Ojo LGA  143968.0  /portal/asc/lga/LPvGvHdlvgi
10  SZSJbgQp79d  Ajeromi/Ifelodun LGA   69526.0  /portal/asc/lga/SZSJbgQp79d
11  SrU5MH6HMIM               Epe LGA   84839.0  /portal/asc/lga/SrU5MH6HMIM
12  UCclb3oBhbL             Ikeja LGA   55329.0  /portal/asc/lga/UCclb3oBhbL
13  WgUVHd6LYlp      Oshodi/Isolo LGA   74277.0  /portal/asc/lga/WgUVHd6LYlp
14  ePAmwPgZitO             Agege LGA   60926.0  /portal/asc/lga/ePAmwPgZitO
15  fhB4ICWDhmX          Alimosho LGA  332293.0  /portal/asc/lga/fhB4ICWDhmX
16  x9npNF7jiEr           Badagry LGA  140402.0  /portal/asc/lga/x9npNF7jiEr
17  ugACc96v8dR      Lagos Island LGA   31524.0  /portal/asc/lga/ugACc96v8dR
18  uhzcCCb85FB           Ikorodu LGA  241112.0  /portal/asc/lga/uhzcCCb85FB
19  yme7mbY3bAw             Apapa LGA   43070.0  /portal/asc/lga/yme7mbY3bAw

['id', 'name', 'learners', 'link']
(20, 4)

In [53]:
oshodi = lagos_children[
    lagos_children["name"].str.contains(
        "Oshodi",
        case=False,
        na=False
    )
]

display(oshodi)

             id              name  learners                         link
13  WgUVHd6LYlp  Oshodi/Isolo LGA   74277.0  /portal/asc/lga/WgUVHd6LYlp

In [54]:
oshodi_link = oshodi.iloc[0]["link"]

print(oshodi_link)

/portal/asc/lga/WgUVHd6LYlp

In [55]:
oshodi_url = site_root + oshodi_link

print(oshodi_url)

https://emis.education.gov.ng/portal/asc/lga/WgUVHd6LYlp

In [58]:
oshodi_manifest_url = "https://emis.education.gov.ng/portal/api/b0f79c25583e514a3cdaee7b84571fcb/589b4c8c281265c348a13b43c5d8b364/all-queries.json"

In [60]:
oshodi_response = requests.get(oshodi_manifest_url)

print("URL:", oshodi_manifest_url)
print("Status:", oshodi_response.status_code)
print("Content-Type:", oshodi_response.headers.get("content-type"))
print("First 100 characters:")
print(oshodi_response.text[:100])

URL: https://emis.education.gov.ng/portal/api/b0f79c25583e514a3cdaee7b84571fcb/589b4c8c281265c348a13b43c5d8b364/all-queries.json
Status: 200
Content-Type: text/html
First 100 characters:
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/s

In [59]:
oshodi_response = requests.get(oshodi_manifest_url)

print("Status:", oshodi_response.status_code)
print("Content-Type:", oshodi_response.headers.get("content-type"))

oshodi_manifest = oshodi_response.json()

print("Entries:", len(oshodi_manifest))
print(list(oshodi_manifest.keys())[:30])

Status: 200
Content-Type: text/html

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [61]:
test_response = requests.get(
    oshodi_manifest_url,
    allow_redirects=False
)

print("Status:", test_response.status_code)
print("Content-Type:", test_response.headers.get("content-type"))
print("Location:", test_response.headers.get("location"))
print("Response URL:", test_response.url)

Status: 200
Content-Type: text/html
Location: None
Response URL: https://emis.education.gov.ng/portal/api/b0f79c25583e514a3cdaee7b84571fcb/589b4c8c281265c348a13b43c5d8b364/all-queries.json

In [62]:
print("Redirect history:", oshodi_response.history)
print("Final URL:", oshodi_response.url)

Redirect history: []
Final URL: https://emis.education.gov.ng/portal/api/b0f79c25583e514a3cdaee7b84571fcb/589b4c8c281265c348a13b43c5d8b364/all-queries.json

In [63]:
oshodi_headers = {
    "Accept": "*/*",
    "Referer": "https://emis.education.gov.ng/portal/asc/lga/WgUVHd6LYlp/",
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/154.0.0.0 Safari/537.36"
    ),
}

In [64]:
oshodi_response = requests.get(
    oshodi_manifest_url,
    headers=oshodi_headers,
    timeout=30
)

print("Status:", oshodi_response.status_code)
print("Content-Type:", oshodi_response.headers.get("content-type"))
print("First 100 characters:")
print(oshodi_response.text[:100])

Status: 200
Content-Type: text/html
First 100 characters:
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/s

In [65]:
oshodi_headers = {
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://emis.education.gov.ng/portal/asc/lga/WgUVHd6LYlp/",
    "Sec-CH-UA": '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
    "Sec-CH-UA-Mobile": "?0",
    "Sec-CH-UA-Platform": '"Windows"',
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/154.0.0.0 Safari/537.36"
    ),
}

In [66]:
oshodi_response = requests.get(
    oshodi_manifest_url,
    headers=oshodi_headers,
    timeout=30
)

print("Status:", oshodi_response.status_code)
print("Content-Type:", oshodi_response.headers.get("content-type"))
print("First 100 characters:")
print(oshodi_response.text[:100])

Status: 200
Content-Type: text/html
First 100 characters:
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/s

In [67]:
session = requests.Session()

session.headers.update(oshodi_headers)

page_response = session.get(
    "https://emis.education.gov.ng/portal/asc/lga/WgUVHd6LYlp/",
    timeout=30
)

print("Page:", page_response.status_code)
print("Cookies:", session.cookies.get_dict())

Page: 200
Cookies: {}

In [68]:
oshodi_response = session.get(
    oshodi_manifest_url,
    timeout=30
)

print("Manifest status:", oshodi_response.status_code)
print("Manifest type:", oshodi_response.headers.get("content-type"))
print(oshodi_response.text[:100])

Manifest status: 200
Manifest type: text/html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/s

In [69]:
oshodi_manifest_url = "https://emis.education.gov.ng/portal/api/b0f79c25583e514a3cdaee7b84571fcb/589b4c8c281265c348a13b43c5d8b364/all-queries.json"

In [70]:
print(oshodi_manifest_url)
print(
    "Correct ending:",
    oshodi_manifest_url.endswith("all-queries.json")
)

https://emis.education.gov.ng/portal/api/b0f79c25583e514a3cdaee7b84571fcb/589b4c8c281265c348a13b43c5d8b364/all-queries.json
Correct ending: True

In [71]:
oshodi_response = requests.get(
    oshodi_manifest_url,
    timeout=30
)

print("Status:", oshodi_response.status_code)
print(
    "Content-Type:",
    oshodi_response.headers.get("content-type")
)
print(oshodi_response.text[:100])

Status: 200
Content-Type: text/html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/s

In [72]:
dx_url = "https://emis.education.gov.ng/portal/data/census/dx/7ee767038ec62a0374c14189ad8d32b3/dx.parquet"

In [73]:
dx_response = requests.get(dx_url, timeout=30)

print("Status:", dx_response.status_code)
print("Content-Type:", dx_response.headers.get("content-type"))
print("Size:", len(dx_response.content))
print("First 16 bytes:", dx_response.content[:16])

Status: 200
Content-Type: application/octet-stream
Size: 1944
First 16 bytes: b'PAR1\x15\x00\x15\x84\x14\x15\xb0\x0c,\x15\xaa\x01'

In [74]:
from pathlib import Path

oshodi_raw_dir = Path(
    "../data/raw/dnemis/2024_2025/states/lagos/lgas/oshodi_isolo"
)

oshodi_raw_dir.mkdir(parents=True, exist_ok=True)

print(oshodi_raw_dir)

..\data\raw\dnemis\2024_2025\states\lagos\lgas\oshodi_isolo

In [75]:
dx_path = oshodi_raw_dir / "dx.parquet"
dx_path.write_bytes(dx_response.content)

print("Saved:", dx_path)

Saved: ..\data\raw\dnemis\2024_2025\states\lagos\lgas\oshodi_isolo\dx.parquet

In [76]:
with open(dx_path, "rb") as f:
    print(f.read(4))

b'PAR1'

In [77]:
import pandas as pd

dx_df = pd.read_parquet(dx_path)

print("Shape:", dx_df.shape)
print("Columns:", dx_df.columns.tolist())

display(dx_df.head(20))

Shape: (85, 2)
Columns: ['id', 'name']

             id                                     name
0   d8qCE7aPWtD                        ASC-PRY Enrolment
1   Qwjg1QG0Hws                  ASC-PRY Enrolment girls
2   uXpZ0iaeH4P                          ASC-PRY Dropout
3   QETjPTty02O                      ASC-PRY Dropout (%)
4   Mmn0SEDyzOC      ASC-PRY Learners with special needs
5   DANh9bP86R9  ASC-PRY Learners with special needs (%)
6   uNvBLdtslJ5     ASC-PRY Learner-stream ratio (ratio)
7   aX6SpmH2icc                          ASC-PRY Orphans
8   JH1hYfoV2hb              ASC-PRY Female learners (%)
9   yjH9LAuAMrk                   ASC-PRY Enrolment boys
10  zGdBeuyjOeQ                      ASC-PRY Orphans (%)
11  wDf8ZOwWgib                        ASC-JSS Enrolment
12  AoOq7RrHxMr                          ASC-JSS Dropout
13  nghVrzkls6X              ASC-JSS Female learners (%)
14  gAfSf7sfxib                   ASC-JSS Enrolment boys
15  bCMrPV3785Y      ASC-JSS Learners with special needs
16  uSfibhbGRT1                  ASC-JSS Enrolment girls
17  Yf6K5jD4oED     ASC-JSS Learner-stream ratio (ratio)
18  eLOZ1cSBHJM  ASC-JSS Learners with special needs (%)
19  IYNEmLyFgbe                        ASC-SSS Enrolment

In [78]:
decoded_kpis = (
    kpis_data
    .merge(
        dx_df,
        left_on="dx",
        right_on="id",
        how="left"
    )
)

display(decoded_kpis)

            dx       value           id                             name
0  jwjKmtVK2wj  39825932.0  jwjKmtVK2wj   ASC-GEN Enrolment (all levels)
1  Dw7f4gs9RcS   1185610.0  Dw7f4gs9RcS                 ASC-GEN Teachers
2  DvMfSq5pZSA    725778.0  DvMfSq5pZSA  ASC-GEN Usable classrooms (F.2)
3  vDmeu4io2Fs    604479.0  vDmeu4io2Fs     ASC-GEN Usable toilets (F.2)

In [79]:
decoded_kpis = decoded_kpis[
    ["dx", "name", "value"]
]

display(decoded_kpis)

            dx                             name       value
0  jwjKmtVK2wj   ASC-GEN Enrolment (all levels)  39825932.0
1  Dw7f4gs9RcS                 ASC-GEN Teachers   1185610.0
2  DvMfSq5pZSA  ASC-GEN Usable classrooms (F.2)    725778.0
3  vDmeu4io2Fs     ASC-GEN Usable toilets (F.2)    604479.0

In [80]:
keywords = [
    "enrol",
    "teacher",
    "classroom",
    "school"
]

capacity_indicators = dx_df[
    dx_df["name"]
    .str.lower()
    .str.contains("|".join(keywords), na=False)
]

display(capacity_indicators)

             id                                    name
0   d8qCE7aPWtD                       ASC-PRY Enrolment
1   Qwjg1QG0Hws                 ASC-PRY Enrolment girls
9   yjH9LAuAMrk                  ASC-PRY Enrolment boys
11  wDf8ZOwWgib                       ASC-JSS Enrolment
14  gAfSf7sfxib                  ASC-JSS Enrolment boys
16  uSfibhbGRT1                 ASC-JSS Enrolment girls
19  IYNEmLyFgbe                       ASC-SSS Enrolment
21  i8dMJSyq5hO                  ASC-SSS Enrolment boys
25  g1ozV2n8G88                      ASC-ANFE Enrolment
27  vZA5RaodnuH                 ASC-SSS Enrolment girls
29  kxJmBoDtD9t                 ASC-ANFE Enrolment boys
31  jwjKmtVK2wj          ASC-GEN Enrolment (all levels)
34  VzPMQzTjenn                ASC-ANFE Enrolment girls
42  XZEG3yT7WmJ                  ASC-GEN Teachers, male
43  Dw7f4gs9RcS                        ASC-GEN Teachers
44  Exv6Kz1TXmJ                ASC-GEN Teachers, female
46  eie1tIO5HtX   ASC-GEN Learner-teacher ratio (ratio)
47  zKAZUEGYL52    ASC-GEN Enrolment males (all levels)
50  HxRedgvSK2M  ASC-GEN Enrolment females (all levels)
52  CKMgwHERBfg             MD: ANFE (IQS/IQTE) schools
55  wVjDYI2HuQb                       MD: Total schools
58  DvMfSq5pZSA         ASC-GEN Usable classrooms (F.2)
60  v31dkf4PhmH                     MD: Primary schools
61  uDBB1WrCkST               MD: Sci/Tech/ Voc schools
62  U8ytqWQMFwD                      MD: Public schools
64  BXTUMWSq4zQ                     MD: Private schools
67  tuku316VSXL                          MD: SS schools
68  I8JeN23lKHn                          MD: JS schools
71  q5mnwKasEpF  MD: Private schools - Expected Reports
72  YN2pzjKpi3l           Learners per classroom(subex)
74  PbzDc38hOsx               MD: Total female teachers
78  Jx7wWJI1WpR    MD: Private schools - Actual Reports
81  j3cxHeBhZ4m                  ASC-STC Enrolment boys
82  ABJrmFcIpT3                      MD: Total teachers
83  STJaOAJl6eG                 ASC-STC Enrolment girls
84  u4ogrV7WUcz                       ASC-STC Enrolment

In [81]:
teacher_indicators = dx_df[
    dx_df["name"].str.contains(
        "teacher",
        case=False,
        na=False
    )
]

display(teacher_indicators)

             id                                   name
42  XZEG3yT7WmJ                 ASC-GEN Teachers, male
43  Dw7f4gs9RcS                       ASC-GEN Teachers
44  Exv6Kz1TXmJ               ASC-GEN Teachers, female
46  eie1tIO5HtX  ASC-GEN Learner-teacher ratio (ratio)
74  PbzDc38hOsx              MD: Total female teachers
82  ABJrmFcIpT3                     MD: Total teachers

In [82]:
classroom_indicators = dx_df[
    dx_df["name"].str.contains(
        "classroom",
        case=False,
        na=False
    )
]

display(classroom_indicators)

             id                             name
58  DvMfSq5pZSA  ASC-GEN Usable classrooms (F.2)
72  YN2pzjKpi3l    Learners per classroom(subex)

In [83]:
enrolment_indicators = dx_df[
    dx_df["name"].str.contains(
        "enrol",
        case=False,
        na=False
    )
]

display(enrolment_indicators)

             id                                    name
0   d8qCE7aPWtD                       ASC-PRY Enrolment
1   Qwjg1QG0Hws                 ASC-PRY Enrolment girls
9   yjH9LAuAMrk                  ASC-PRY Enrolment boys
11  wDf8ZOwWgib                       ASC-JSS Enrolment
14  gAfSf7sfxib                  ASC-JSS Enrolment boys
16  uSfibhbGRT1                 ASC-JSS Enrolment girls
19  IYNEmLyFgbe                       ASC-SSS Enrolment
21  i8dMJSyq5hO                  ASC-SSS Enrolment boys
25  g1ozV2n8G88                      ASC-ANFE Enrolment
27  vZA5RaodnuH                 ASC-SSS Enrolment girls
29  kxJmBoDtD9t                 ASC-ANFE Enrolment boys
31  jwjKmtVK2wj          ASC-GEN Enrolment (all levels)
34  VzPMQzTjenn                ASC-ANFE Enrolment girls
47  zKAZUEGYL52    ASC-GEN Enrolment males (all levels)
50  HxRedgvSK2M  ASC-GEN Enrolment females (all levels)
81  j3cxHeBhZ4m                  ASC-STC Enrolment boys
83  STJaOAJl6eG                 ASC-STC Enrolment girls
84  u4ogrV7WUcz                       ASC-STC Enrolment

In [84]:
decoded_kpis = (
    kpis_data
    .merge(
        dx_df,
        left_on="dx",
        right_on="id",
        how="left"
    )
)

display(decoded_kpis[["dx", "name", "value"]])

            dx                             name       value
0  jwjKmtVK2wj   ASC-GEN Enrolment (all levels)  39825932.0
1  Dw7f4gs9RcS                 ASC-GEN Teachers   1185610.0
2  DvMfSq5pZSA  ASC-GEN Usable classrooms (F.2)    725778.0
3  vDmeu4io2Fs     ASC-GEN Usable toilets (F.2)    604479.0

In [85]:
constants_url = "https://emis.education.gov.ng/portal/data/census/constants/ece25d79995506f36891ed868e4ed923/constants.parquet"

constants_response = requests.get(
    constants_url,
    timeout=30
)

print("Status:", constants_response.status_code)
print(
    "Content-Type:",
    constants_response.headers.get("content-type")
)
print("Size:", len(constants_response.content))
print("First 4 bytes:", constants_response.content[:4])

Status: 200
Content-Type: application/octet-stream
Size: 687
First 4 bytes: b'PAR1'

In [86]:
constants_path = oshodi_raw_dir / "constants.parquet"

constants_path.write_bytes(
    constants_response.content
)

print("Saved:", constants_path)

Saved: ..\data\raw\dnemis\2024_2025\states\lagos\lgas\oshodi_isolo\constants.parquet

In [87]:
constants_df = pd.read_parquet(constants_path)

print("Shape:", constants_df.shape)
print("Columns:", constants_df.columns.tolist())

display(constants_df.head(30))

Shape: (3, 3)
Columns: ['id', 'name', 'value']

            id                                   name  value
0  UBEstdLTR01    UBE standard: learner-teacher ratio   35.0
1  UBEstdLCR01  UBE standard: learner-classroom ratio   35.0
2  UBEstdLToR1     UBE standard: learner-toilet ratio   30.0

In [88]:
ou_url = "https://emis.education.gov.ng/portal/data/census/ou/58331b859583c87ea49c3a0dad9499bc/ou.parquet"

ou_response = requests.get(
    ou_url,
    timeout=30
)

print("Status:", ou_response.status_code)
print("Type:", ou_response.headers.get("content-type"))
print("Size:", len(ou_response.content))
print("Magic bytes:", ou_response.content[:4])

Status: 200
Type: application/octet-stream
Size: 25682
Magic bytes: b'PAR1'

In [89]:
ou_path = oshodi_raw_dir / "ou.parquet"

ou_path.write_bytes(
    ou_response.content
)

25682

In [90]:
ou_df = pd.read_parquet(ou_path)

print("Shape:", ou_df.shape)
print("Columns:", ou_df.columns.tolist())

display(ou_df.head(20))

Shape: (812, 9)
Columns: ['id', 'name', 'level', 'parent_id', 'parent_name', 'path', 'ty', 'lng', 'lat']

,id,name,level,parent_id,parent_name,path,ty,lng,lat
0,AoCaBHBeXTs,fg Nigeria,1.0,NaN,NaN,/AoCaBHBeXTs,NaN,NaN,NaN
1,M689V9w3Gs3,ke Kebbi State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/M689V9w3Gs3,2.0,NaN,NaN
2,FHlOerryBjk,ab Abia State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/FHlOerryBjk,2.0,NaN,NaN
3,OgjFloqKoqk,ad Adamawa State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/OgjFloqKoqk,2.0,NaN,NaN
4,aMQcvAoEFh0,ed Edo State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/aMQcvAoEFh0,2.0,NaN,NaN
5,cTIw3RXOLCQ,kn Kano State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/cTIw3RXOLCQ,2.0,NaN,NaN
6,uKlacgs9ykR,kt Katsina State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/uKlacgs9ykR,2.0,NaN,NaN
7,BmWTbiMgEai,ri Rivers State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/BmWTbiMgEai,2.0,NaN,NaN
8,FmH4buccgqx,za Zamfara State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/FmH4buccgqx,2.0,NaN,NaN
9,FmOhtDnhdwU,im Imo State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/FmOhtDnhdwU,2.0,NaN,NaN
10,Gq37IyyjUfj,so Sokoto State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/Gq37IyyjUfj,2.0,NaN,NaN
11,H2ZhSMudlMI,la Lagos State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/H2ZhSMudlMI,2.0,NaN,NaN
12,MJVVi73YayJ,ji Jigawa State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/MJVVi73YayJ,2.0,NaN,NaN
13,MXrZyuS9E7A,be Benue State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/MXrZyuS9E7A,2.0,NaN,NaN
14,Nko8QFDmYmq,an Anambra state,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/Nko8QFDmYmq,2.0,NaN,NaN
15,Quac4RHRtaZ,en Enugu State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/Quac4RHRtaZ,2.0,NaN,NaN
16,fBInDsbaQHO,og Ogun State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/fBInDsbaQHO,2.0,NaN,NaN
17,gzLOszDWdqM,na Nasarawa State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/gzLOszDWdqM,2.0,NaN,NaN
18,hfNPq5F4mjr,os Osun State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/hfNPq5F4mjr,2.0,NaN,NaN
19,iilma7EajGc,ek Ekiti State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/iilma7EajGc,2.0,NaN,NaN

In [92]:
pe_url = "https://emis.education.gov.ng/portal/data/census/pe/9cfd8dc4165763c0334362174a98faa9/pe.parquet"

pe_response = requests.get(
    pe_url,
    timeout=30
)

print("Status:", pe_response.status_code)
print("Size:", len(pe_response.content))
print("Magic bytes:", pe_response.content[:4])

Status: 200
Size: 789
Magic bytes: b'PAR1'

In [93]:
pe_path = oshodi_raw_dir / "pe.parquet"
pe_path.write_bytes(pe_response.content)

789

In [94]:
pe_df = pd.read_parquet(pe_path)

print("Shape:", pe_df.shape)
print("Columns:", pe_df.columns.tolist())

display(pe_df.head(20))

Shape: (1, 6)
Columns: ['period', 'periodType', 'year', 'quarter', 'month', 'startDate']

   period periodType    year quarter month  startDate
0  2024.0     YEARLY  2024.0     NaN   NaN 2024-01-01

In [95]:
fact_url = "https://emis.education.gov.ng/portal/data/census/fact/c7b39c9c32ba5e0dce5e0e9f2a288c79/fact.parquet"

fact_response = requests.get(
    fact_url,
    timeout=30
)

print("Status:", fact_response.status_code)
print("Size:", len(fact_response.content))
print("Magic bytes:", fact_response.content[:4])

Status: 200
Size: 147338
Magic bytes: b'PAR1'

In [96]:
fact_path = oshodi_raw_dir / "fact.parquet"
fact_path.write_bytes(fact_response.content)

147338

In [97]:
fact_df = pd.read_parquet(fact_path)

print("Shape:", fact_df.shape)
print("Columns:", fact_df.columns.tolist())

display(fact_df.head(20))

Shape: (52382, 5)
Columns: ['dx', 'ou', 'pe', 'periodType', 'value']

             dx           ou      pe periodType       value
0   d8qCE7aPWtD  AoCaBHBeXTs  2024.0     YEARLY  29002071.0
1   yjH9LAuAMrk  AoCaBHBeXTs  2024.0     YEARLY  14662152.0
2   Qwjg1QG0Hws  AoCaBHBeXTs  2024.0     YEARLY  14339919.0
3   JH1hYfoV2hb  AoCaBHBeXTs  2024.0     YEARLY        49.4
4   uNvBLdtslJ5  AoCaBHBeXTs  2024.0     YEARLY        18.0
5   Mmn0SEDyzOC  AoCaBHBeXTs  2024.0     YEARLY    295864.0
6   DANh9bP86R9  AoCaBHBeXTs  2024.0     YEARLY         1.0
7   uXpZ0iaeH4P  AoCaBHBeXTs  2024.0     YEARLY    348139.0
8   QETjPTty02O  AoCaBHBeXTs  2024.0     YEARLY         1.5
9   aX6SpmH2icc  AoCaBHBeXTs  2024.0     YEARLY   1354630.0
10  zGdBeuyjOeQ  AoCaBHBeXTs  2024.0     YEARLY         4.7
11  wDf8ZOwWgib  AoCaBHBeXTs  2024.0     YEARLY   5651481.0
12  gAfSf7sfxib  AoCaBHBeXTs  2024.0     YEARLY   2768078.0
13  uSfibhbGRT1  AoCaBHBeXTs  2024.0     YEARLY   2883403.0
14  nghVrzkls6X  AoCaBHBeXTs  2024.0     YEARLY        51.0
15  Yf6K5jD4oED  AoCaBHBeXTs  2024.0     YEARLY        20.3
16  bCMrPV3785Y  AoCaBHBeXTs  2024.0     YEARLY     36070.0
17  eLOZ1cSBHJM  AoCaBHBeXTs  2024.0     YEARLY         0.6
18  AoOq7RrHxMr  AoCaBHBeXTs  2024.0     YEARLY     70933.0
19  CEgyg6JJbNv  AoCaBHBeXTs  2024.0     YEARLY         1.3

In [98]:
print(ou_df.shape)
print(ou_df.columns.tolist())
display(ou_df.head())

print(pe_df.shape)
print(pe_df.columns.tolist())
display(pe_df.head())

print(fact_df.shape)
print(fact_df.columns.tolist())
display(fact_df.head())

(812, 9)
['id', 'name', 'level', 'parent_id', 'parent_name', 'path', 'ty', 'lng', 'lat']

,id,name,level,parent_id,parent_name,path,ty,lng,lat
0,AoCaBHBeXTs,fg Nigeria,1.0,NaN,NaN,/AoCaBHBeXTs,NaN,NaN,NaN
1,M689V9w3Gs3,ke Kebbi State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/M689V9w3Gs3,2.0,NaN,NaN
2,FHlOerryBjk,ab Abia State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/FHlOerryBjk,2.0,NaN,NaN
3,OgjFloqKoqk,ad Adamawa State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/OgjFloqKoqk,2.0,NaN,NaN
4,aMQcvAoEFh0,ed Edo State,2.0,AoCaBHBeXTs,fg Nigeria,/AoCaBHBeXTs/aMQcvAoEFh0,2.0,NaN,NaN

(1, 6)
['period', 'periodType', 'year', 'quarter', 'month', 'startDate']

   period periodType    year quarter month  startDate
0  2024.0     YEARLY  2024.0     NaN   NaN 2024-01-01

(52382, 5)
['dx', 'ou', 'pe', 'periodType', 'value']

            dx           ou      pe periodType       value
0  d8qCE7aPWtD  AoCaBHBeXTs  2024.0     YEARLY  29002071.0
1  yjH9LAuAMrk  AoCaBHBeXTs  2024.0     YEARLY  14662152.0
2  Qwjg1QG0Hws  AoCaBHBeXTs  2024.0     YEARLY  14339919.0
3  JH1hYfoV2hb  AoCaBHBeXTs  2024.0     YEARLY        49.4
4  uNvBLdtslJ5  AoCaBHBeXTs  2024.0     YEARLY        18.0

In [99]:
fact_decoded = (
    fact_df
    .merge(
        dx_df,
        left_on="dx",
        right_on="id",
        how="left",
        suffixes=("", "_dx")
    )
    .merge(
        ou_df,
        left_on="ou",
        right_on="id",
        how="left",
        suffixes=("", "_ou")
    )
)

display(
    fact_decoded[
        [
            "dx",
            "name",
            "ou",
            "name_ou",
            "level",
            "pe",
            "value"
        ]
    ].head(20)
)

,dx,name,ou,name_ou,level,pe,value
0,d8qCE7aPWtD,ASC-PRY Enrolment,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,29002071.0
1,yjH9LAuAMrk,ASC-PRY Enrolment boys,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,14662152.0
2,Qwjg1QG0Hws,ASC-PRY Enrolment girls,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,14339919.0
3,JH1hYfoV2hb,ASC-PRY Female learners (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,49.4
4,uNvBLdtslJ5,ASC-PRY Learner-stream ratio (ratio),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,18.0
5,Mmn0SEDyzOC,ASC-PRY Learners with special needs,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,295864.0
6,DANh9bP86R9,ASC-PRY Learners with special needs (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,1.0
7,uXpZ0iaeH4P,ASC-PRY Dropout,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,348139.0
8,QETjPTty02O,ASC-PRY Dropout (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,1.5
9,aX6SpmH2icc,ASC-PRY Orphans,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,1354630.0
10,zGdBeuyjOeQ,ASC-PRY Orphans (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,4.7
11,wDf8ZOwWgib,ASC-JSS Enrolment,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,5651481.0
12,gAfSf7sfxib,ASC-JSS Enrolment boys,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,2768078.0
13,uSfibhbGRT1,ASC-JSS Enrolment girls,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,2883403.0
14,nghVrzkls6X,ASC-JSS Female learners (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,51.0
15,Yf6K5jD4oED,ASC-JSS Learner-stream ratio (ratio),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,20.3
16,bCMrPV3785Y,ASC-JSS Learners with special needs,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,36070.0
17,eLOZ1cSBHJM,ASC-JSS Learners with special needs (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,0.6
18,AoOq7RrHxMr,ASC-JSS Dropout,AoCaBHBeXTs,fg Nigeria,1.0,2024.0,70933.0
19,CEgyg6JJbNv,ASC-JSS Dropout (%),AoCaBHBeXTs,fg Nigeria,1.0,2024.0,1.3

In [100]:
ou_df["level"].value_counts().sort_index()

level
1.0      1
2.0     37
3.0    774
Name: count, dtype: int64

In [101]:
ou_df.groupby("level")["name"].count()

level
1.0      1
2.0     37
3.0    774
Name: name, dtype: int64

In [102]:
lga_units = ou_df[ou_df["level"] == 3]

print(lga_units.shape)
display(lga_units.head(20))

(774, 9)

,id,name,level,parent_id,parent_name,path,ty,lng,lat
38,BNszdgYq8u6,ko Okene LGA,3.0,S7Vs7ifJKlh,ko Kogi State,/AoCaBHBeXTs/S7Vs7ifJKlh/BNszdgYq8u6,NaN,NaN,NaN
39,aMECb81TXIz,im Mbaitoli LGA,3.0,FmOhtDnhdwU,im Imo State,/AoCaBHBeXTs/FmOhtDnhdwU/aMECb81TXIz,NaN,NaN,NaN
40,paJD0qSggAn,de Okpe LGA,3.0,m0rZG06GdPe,de Delta State,/AoCaBHBeXTs/m0rZG06GdPe/paJD0qSggAn,NaN,NaN,NaN
41,As3MjkIqRgV,ri Gokana LGA,3.0,BmWTbiMgEai,ri Rivers State,/AoCaBHBeXTs/BmWTbiMgEai/As3MjkIqRgV,NaN,NaN,NaN
42,AhMtxuQDl0d,be Obi LGA,3.0,MXrZyuS9E7A,be Benue State,/AoCaBHBeXTs/MXrZyuS9E7A/AhMtxuQDl0d,2.0,NaN,NaN
43,uCfN8gLOWni,ta Gashaka LGA,3.0,jXngIDniC8t,ta Taraba State,/AoCaBHBeXTs/jXngIDniC8t/uCfN8gLOWni,2.0,NaN,NaN
44,AGXqsKdBKI5,kn Rano LGA,3.0,cTIw3RXOLCQ,kn Kano State,/AoCaBHBeXTs/cTIw3RXOLCQ/AGXqsKdBKI5,2.0,NaN,NaN
45,DHKG4lUpV4W,og Yewa South LGA,3.0,fBInDsbaQHO,og Ogun State,/AoCaBHBeXTs/fBInDsbaQHO/DHKG4lUpV4W,NaN,NaN,NaN
46,AeNgbe9Q91U,ke Augie LGA,3.0,M689V9w3Gs3,ke Kebbi State,/AoCaBHBeXTs/M689V9w3Gs3/AeNgbe9Q91U,2.0,NaN,NaN
47,Phmk9OjyhlF,la Ibeju/Lekki LGA,3.0,H2ZhSMudlMI,la Lagos State,/AoCaBHBeXTs/H2ZhSMudlMI/Phmk9OjyhlF,NaN,NaN,NaN
48,RGiMttErs00,ji Hadejia LGA,3.0,MJVVi73YayJ,ji Jigawa State,/AoCaBHBeXTs/MJVVi73YayJ/RGiMttErs00,2.0,NaN,NaN
49,trFj7NJV7eb,kt Danja LGA,3.0,uKlacgs9ykR,kt Katsina State,/AoCaBHBeXTs/uKlacgs9ykR/trFj7NJV7eb,2.0,NaN,NaN
50,wvrTERNJ55l,la Lagos Mainland LGA,3.0,H2ZhSMudlMI,la Lagos State,/AoCaBHBeXTs/H2ZhSMudlMI/wvrTERNJ55l,2.0,NaN,NaN
51,fNhA5TKBeUW,og Sagamu LGA,3.0,fBInDsbaQHO,og Ogun State,/AoCaBHBeXTs/fBInDsbaQHO/fNhA5TKBeUW,NaN,NaN,NaN
52,OaX5jg5snSa,ri Ahoada East LGA,3.0,BmWTbiMgEai,ri Rivers State,/AoCaBHBeXTs/BmWTbiMgEai/OaX5jg5snSa,NaN,NaN,NaN
53,GdPEtVSft8z,ko Lokoja LGA,3.0,S7Vs7ifJKlh,ko Kogi State,/AoCaBHBeXTs/S7Vs7ifJKlh/GdPEtVSft8z,NaN,NaN,NaN
54,Z3t6VtZEOA3,yo Potiskum LGA,3.0,Ym1fEhWFWYI,yo Yobe State,/AoCaBHBeXTs/Ym1fEhWFWYI/Z3t6VtZEOA3,NaN,NaN,NaN
55,jcDcQsnT8hO,ab Umunneochi LGA,3.0,FHlOerryBjk,ab Abia State,/AoCaBHBeXTs/FHlOerryBjk/jcDcQsnT8hO,NaN,NaN,NaN
56,cwVYVQXgOzu,im Ahiazu-Mbaise LGA,3.0,FmOhtDnhdwU,im Imo State,/AoCaBHBeXTs/FmOhtDnhdwU/cwVYVQXgOzu,2.0,NaN,NaN
57,ll1ynbwy5yC,ko Idah LGA,3.0,S7Vs7ifJKlh,ko Kogi State,/AoCaBHBeXTs/S7Vs7ifJKlh/ll1ynbwy5yC,NaN,NaN,NaN

In [103]:
lagos_lgas = ou_df[
    (ou_df["level"] == 3)
    & (ou_df["parent_name"].str.contains("Lagos", case=False, na=False))
]

print(lagos_lgas.shape)
display(lagos_lgas[["id", "name", "parent_name"]])

(20, 9)

              id                     name     parent_name
47   Phmk9OjyhlF       la Ibeju/Lekki LGA  la Lagos State
50   wvrTERNJ55l    la Lagos Mainland LGA  la Lagos State
75   WjXjgXuzaRw           la Shomolu LGA  la Lagos State
83   FNBnbVdc4QR           la Eti-Osa LGA  la Lagos State
193  O7v1DtGbdbK          la Surulere LGA  la Lagos State
253  bz52b77hwoM            la Mushin LGA  la Lagos State
321  qCnM7T01dCn            la Kosofe LGA  la Lagos State
383  Isx2W2hs7r0      la Amuwo Odofin LGA  la Lagos State
453  KOlYwQZTBzv       la Ifako/Ijaye LGA  la Lagos State
458  LPvGvHdlvgi               la Ojo LGA  la Lagos State
531  SZSJbgQp79d  la Ajeromi/Ifelodun LGA  la Lagos State
537  SrU5MH6HMIM               la Epe LGA  la Lagos State
538  UCclb3oBhbL             la Ikeja LGA  la Lagos State
545  WgUVHd6LYlp      la Oshodi/Isolo LGA  la Lagos State
571  ePAmwPgZitO             la Agege LGA  la Lagos State
573  fhB4ICWDhmX          la Alimosho LGA  la Lagos State
607  x9npNF7jiEr           la Badagry LGA  la Lagos State
791  ugACc96v8dR      la Lagos Island LGA  la Lagos State
792  uhzcCCb85FB           la Ikorodu LGA  la Lagos State
804  yme7mbY3bAw             la Apapa LGA  la Lagos State

In [104]:
fact_ownership_url = "https://emis.education.gov.ng/portal/data/census/fact_ownership/7575be6ef1c25be5e42d0100637dcaf1/fact_ownership.parquet"

In [105]:
fact_ownership_response = requests.get(
    fact_ownership_url,
    timeout=30
)

print("Status:", fact_ownership_response.status_code)
print("Content-Type:", fact_ownership_response.headers.get("content-type"))
print("Size:", len(fact_ownership_response.content))
print("Magic bytes:", fact_ownership_response.content[:4])

Status: 200
Content-Type: application/octet-stream
Size: 125347
Magic bytes: b'PAR1'

In [106]:
fact_ownership_path = oshodi_raw_dir / "fact_ownership.parquet"

fact_ownership_path.write_bytes(
    fact_ownership_response.content
)

print("Saved:", fact_ownership_path)

Saved: ..\data\raw\dnemis\2024_2025\states\lagos\lgas\oshodi_isolo\fact_ownership.parquet

In [107]:
fact_ownership_df = pd.read_parquet(
    fact_ownership_path
)

In [108]:
print("Shape:", fact_ownership_df.shape)
print("Columns:", fact_ownership_df.columns.tolist())

display(fact_ownership_df.head(20))

Shape: (36498, 7)
Columns: ['dx', 'ou', 'pe', 'periodType', 'category_id', 'category_name', 'value']

,dx,ou,pe,periodType,category_id,category_name,value
0,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,8268914.0
1,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,31542433.0
2,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,gGWkqoE2inU,Unknown ownership,1070.0
3,Dw7f4gs9RcS,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,600167.0
4,Dw7f4gs9RcS,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,585092.0
5,Dw7f4gs9RcS,AoCaBHBeXTs,2024.0,YEARLY,gGWkqoE2inU,Unknown ownership,129.0
6,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,13.8
7,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,53.9
8,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,gGWkqoE2inU,Unknown ownership,8.3
9,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,50.4
10,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,49.4
11,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,gGWkqoE2inU,Unknown ownership,47.7
12,HxRedgvSK2M,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,4167214.0
13,HxRedgvSK2M,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,15576404.0
14,HxRedgvSK2M,AoCaBHBeXTs,2024.0,YEARLY,gGWkqoE2inU,Unknown ownership,510.0
15,d8qCE7aPWtD,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,5904049.0
16,d8qCE7aPWtD,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,23097078.0
17,d8qCE7aPWtD,AoCaBHBeXTs,2024.0,YEARLY,gGWkqoE2inU,Unknown ownership,257.0
18,Qwjg1QG0Hws,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,2963963.0
19,Qwjg1QG0Hws,AoCaBHBeXTs,2024.0,YEARLY,qi6ZMPx12iM,Public,11375461.0

In [109]:
fact_schooltype_url = "https://emis.education.gov.ng/portal/data/census/fact_schooltype/204b75f07491db43a0af14149d4ae9ad/fact_schooltype.parquet"

In [110]:
fact_schooltype_response = requests.get(
    fact_schooltype_url,
    timeout=30
)

print("Status:", fact_schooltype_response.status_code)
print("Magic bytes:", fact_schooltype_response.content[:4])

Status: 200
Magic bytes: b'PAR1'

In [111]:
fact_schooltype_path = oshodi_raw_dir / "fact_schooltype.parquet"

fact_schooltype_path.write_bytes(
    fact_schooltype_response.content
)

95517

In [112]:
fact_schooltype_df = pd.read_parquet(
    fact_schooltype_path
)

print("Shape:", fact_schooltype_df.shape)
print("Columns:", fact_schooltype_df.columns.tolist())

display(fact_schooltype_df.head(20))

Shape: (24158, 7)
Columns: ['dx', 'ou', 'pe', 'periodType', 'category_id', 'category_name', 'value']

,dx,ou,pe,periodType,category_id,category_name,value
0,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,1070.0
1,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,4337718.0
2,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,146184.0
3,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,23056236.0
4,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,8261188.0
5,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,3070775.0
6,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,906929.0
7,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,47.7
8,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,51.1
9,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,33.3
10,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,49.2
11,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,50.4
12,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,50.3
13,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,44.1
14,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,8.3
15,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,35.8
16,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,21.4
17,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,66.7
18,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,13.8
19,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,27.7

In [113]:
fact_typeown_url = "https://emis.education.gov.ng/portal/data/census/fact_typeown/c1822fcb8efc2a56c33b70ca1e013b7d/fact_typeown.parquet"

In [114]:
fact_typeown_response = requests.get(
    fact_typeown_url,
    timeout=30
)

print("Status:", fact_typeown_response.status_code)
print("Magic bytes:", fact_typeown_response.content[:4])

Status: 200
Magic bytes: b'PAR1'

In [115]:
fact_typeown_path = oshodi_raw_dir / "fact_typeown.parquet"

fact_typeown_path.write_bytes(
    fact_typeown_response.content
)

101665

In [116]:
fact_typeown_df = pd.read_parquet(
    fact_typeown_path
)

print("Shape:", fact_typeown_df.shape)
print("Columns:", fact_typeown_df.columns.tolist())

display(fact_typeown_df.head(20))

Shape: (24299, 9)
Columns: ['dx', 'ou', 'pe', 'periodType', 'cat1_id', 'cat1_name', 'cat2_id', 'cat2_name', 'value']

,dx,ou,pe,periodType,cat1_id,cat1_name,cat2_id,cat2_name,value
0,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,gGWkqoE2inU,Unknown ownership,1070.0
1,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,qi6ZMPx12iM,Public,4330381.0
2,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,RYChRe8PgA6,Private,3355.0
3,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,qi6ZMPx12iM,Public,146184.0
4,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,qi6ZMPx12iM,Public,23052836.0
5,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,RYChRe8PgA6,Private,3400.0
6,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,RYChRe8PgA6,Private,8261188.0
7,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,qi6ZMPx12iM,Public,3067890.0
8,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,RYChRe8PgA6,Private,971.0
9,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,qi6ZMPx12iM,Public,906929.0
10,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,gGWkqoE2inU,Unknown ownership,47.7
11,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,qi6ZMPx12iM,Public,51.1
12,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,RYChRe8PgA6,Private,51.6
13,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,qi6ZMPx12iM,Public,33.3
14,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,qi6ZMPx12iM,Public,49.2
15,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,RYChRe8PgA6,Private,51.6
16,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,RYChRe8PgA6,Private,50.4
17,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,qi6ZMPx12iM,Public,50.3
18,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,RYChRe8PgA6,Private,49.8
19,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,qi6ZMPx12iM,Public,44.1

In [117]:
print("Shape:", fact_schooltype_df.shape)
print("Columns:", fact_schooltype_df.columns.tolist())

display(fact_schooltype_df.head(20))

Shape: (24158, 7)
Columns: ['dx', 'ou', 'pe', 'periodType', 'category_id', 'category_name', 'value']

,dx,ou,pe,periodType,category_id,category_name,value
0,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,1070.0
1,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,4337718.0
2,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,146184.0
3,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,23056236.0
4,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,8261188.0
5,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,3070775.0
6,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,906929.0
7,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,47.7
8,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,51.1
9,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,33.3
10,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,49.2
11,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,50.4
12,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,50.3
13,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,44.1
14,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,8.3
15,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,35.8
16,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,21.4
17,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,66.7
18,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,13.8
19,eie1tIO5HtX,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,27.7

In [118]:
fact_schooltype_df["category_name"].value_counts()

category_name
Pre2/Primary           6028
Private                5685
JSS                    5653
SSS                    4865
TECH/VOC               1152
IQS/IQTE                751
Unknown school type      24
Name: count, dtype: int64

In [119]:
fact_schooltype_df["category_name"].unique()

<ArrowStringArray>
['Unknown school type',                 'JSS',            'TECH/VOC',
        'Pre2/Primary',             'Private',                 'SSS',
            'IQS/IQTE']
Length: 7, dtype: str

In [120]:
print("Shape:", fact_typeown_df.shape)
print("Columns:", fact_typeown_df.columns.tolist())

display(fact_typeown_df.head(20))

Shape: (24299, 9)
Columns: ['dx', 'ou', 'pe', 'periodType', 'cat1_id', 'cat1_name', 'cat2_id', 'cat2_name', 'value']

,dx,ou,pe,periodType,cat1_id,cat1_name,cat2_id,cat2_name,value
0,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,gGWkqoE2inU,Unknown ownership,1070.0
1,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,qi6ZMPx12iM,Public,4330381.0
2,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,RYChRe8PgA6,Private,3355.0
3,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,qi6ZMPx12iM,Public,146184.0
4,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,qi6ZMPx12iM,Public,23052836.0
5,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,RYChRe8PgA6,Private,3400.0
6,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,RYChRe8PgA6,Private,8261188.0
7,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,qi6ZMPx12iM,Public,3067890.0
8,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,RYChRe8PgA6,Private,971.0
9,jwjKmtVK2wj,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,qi6ZMPx12iM,Public,906929.0
10,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,BkzpJIQugNb,Unknown school type,gGWkqoE2inU,Unknown ownership,47.7
11,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,qi6ZMPx12iM,Public,51.1
12,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,LWv2iy1xoW5,JSS,RYChRe8PgA6,Private,51.6
13,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,buScFFQAJ1g,TECH/VOC,qi6ZMPx12iM,Public,33.3
14,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,qi6ZMPx12iM,Public,49.2
15,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,Q9AZ29igB6j,Pre2/Primary,RYChRe8PgA6,Private,51.6
16,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,RYChRe8PgA6,Private,RYChRe8PgA6,Private,50.4
17,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,qi6ZMPx12iM,Public,50.3
18,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,o62AI6qkSgS,SSS,RYChRe8PgA6,Private,49.8
19,Nc9bgbCb6eO,AoCaBHBeXTs,2024.0,YEARLY,QdjMpXKVYEs,IQS/IQTE,qi6ZMPx12iM,Public,44.1

In [121]:
fact_typeown_df["cat1_name"].value_counts()

cat1_name
Pre2/Primary           6085
JSS                    5692
Private                5685
SSS                    4910
TECH/VOC               1152
IQS/IQTE                751
Unknown school type      24
Name: count, dtype: int64

In [122]:
fact_typeown_df["cat2_name"].value_counts()

cat2_name
Public               18442
Private               5833
Unknown ownership       24
Name: count, dtype: int64

In [123]:
fact_typeown_df[
    ["cat1_name", "cat2_name"]
].drop_duplicates().sort_values(
    ["cat1_name", "cat2_name"]
)

             cat1_name          cat2_name
9             IQS/IQTE             Public
2                  JSS            Private
1                  JSS             Public
5         Pre2/Primary            Private
4         Pre2/Primary             Public
6              Private            Private
8                  SSS            Private
7                  SSS             Public
3             TECH/VOC             Public
0  Unknown school type  Unknown ownership